package main

import (
	"strings"
	"testing"
)

func TestSplitMarkdownTableRow(t *testing.T) {
	cells := splitMarkdownTableRow("| ADR-0140 | Title | Accepted | 2026-06-04 | workflow, Codex | - | - | `docs/decisions/ADR-0140-example.md` |")
	if len(cells) != 8 {
		t.Fatalf("expected 8 cells, got %d", len(cells))
	}
	if cells[0] != "ADR-0140" {
		t.Fatalf("unexpected first cell %q", cells[0])
	}
	if got := extractBacktickedPath(cells[7]); got != "docs/decisions/ADR-0140-example.md" {
		t.Fatalf("unexpected path %q", got)
	}
}

func TestMatchADRsUsesAreaAndPathReferences(t *testing.T) {
	packages := []packageInfo{
		{ImportPath: "dxcluster/internal/cluster"},
		{ImportPath: "dxcluster/telnet"},
	}
	records := []adrRecord{
		{
			ID:     "ADR-0002",
			Status: "Accepted",
			Date:   "2026-01-02",
			Area:   "internal/cluster, runtime",
			Path:   "docs/decisions/ADR-0002-cluster.md",
		},
		{
			ID:      "ADR-0001",
			Status:  "Accepted",
			Date:    "2026-01-01",
			Area:    "docs",
			Path:    "docs/decisions/ADR-0001-telnet.md",
			Content: "Related docs: `telnet/README.md`",
		},
		{
			ID:      "ADR-0003",
			Status:  "Accepted",
			Date:    "2026-01-03",
			Area:    "config",
			Path:    "docs/decisions/ADR-0003-config.md",
			Content: "No scoped package reference.",
		},
	}

	matched := matchADRs("dxcluster", packages, records)
	if len(matched) != 2 {
		t.Fatalf("expected 2 matched ADRs, got %d", len(matched))
	}
	if matched[0].Record.ID != "ADR-0002" || !strings.Contains(matched[0].Match, "area:internal/cluster") {
		t.Fatalf("unexpected first match: %+v", matched[0])
	}
	if matched[1].Record.ID != "ADR-0001" || !strings.Contains(matched[1].Match, "path:telnet") {
		t.Fatalf("unexpected second match: %+v", matched[1])
	}
}

func TestRenderMarkdownIsGeneratedOnly(t *testing.T) {
	data := mapData{
		Spec: mapSpec{
			ID:     "sample",
			Title:  "Sample",
			Output: "docs/code-maps/sample.md",
		},
		ModulePath:  "dxcluster",
		Fingerprint: "abc123",
		Packages: []packageInfo{{
			ImportPath: "dxcluster/telnet",
			RelDir:     "telnet",
			GoFiles:    []string{"telnet/server.go"},
		}},
	}

	rendered := renderMarkdown(data)
	for _, want := range []string{
		"<!-- GENERATED by cmd/codemap. Do not edit by hand. -->",
		"- Source fingerprint: `abc123`",
		"## In-Scope Package Edges",
		"## Related ADRs",
	} {
		if !strings.Contains(rendered, want) {
			t.Fatalf("rendered map missing %q\n%s", want, rendered)
		}
	}
	if strings.Contains(strings.ToLower(rendered), "last reviewed") {
		t.Fatalf("rendered map should not contain human review fields")
	}
}
